[package]
name = "websocket_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
futures-util = "0.3.31"
tokio = { version = "1.44.1", features = ["full"] }
tokio-stream = "0.1.17"
tokio-tungstenite = "0.26.2"
url = "2.5.4"
